<a href="https://colab.research.google.com/github/PadmaDeepak/Bio-Insired-Systems/blob/main/parallel_cellular.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

# Step 1: Create a small 5x5 grid (each cell is a node)
# Random cost for moving from one cell to a neighbor
np.random.seed(0)
costs = np.random.randint(1, 10, (5, 5))

# Step 2: Initialize distance grid
# Start point = top-left (0,0)
# Goal = bottom-right (4,4)
distances = np.full((5, 5), np.inf)
distances[0, 0] = 0  # starting point

def get_neighbors(i, j, shape):
    neighbors = []
    for di, dj in [(-1,0),(1,0),(0,-1),(0,1)]:
        ni, nj = i+di, j+dj
        if 0 <= ni < shape[0] and 0 <= nj < shape[1]:
            neighbors.append((ni, nj))
    return neighbors

# Step 3: Parallel update rule
def update_distances(distances, costs):
    new_distances = distances.copy()
    for i in range(costs.shape[0]):
        for j in range(costs.shape[1]):
            neighbors = get_neighbors(i, j, costs.shape)
            neighbor_values = [distances[x, y] + costs[i, j] for x, y in neighbors]
            best_val = min([distances[i, j]] + neighbor_values)
            new_distances[i, j] = best_val
    return new_distances

# Step 4: Iterate until convergence
for step in range(10):
    new_distances = update_distances(distances, costs)
    if np.allclose(new_distances, distances):
        print(f"Converged after {step+1} iterations.")
        break
    distances = new_distances

# Step 5: Print results
print("Cost Grid (each cell's movement cost):")
print(costs)
print("\nShortest Distance to Goal (Parallel Cellular Computation):")
print(np.round(distances, 2))
print(f"\nEstimated shortest distance from start to goal: {distances[-1, -1]:.2f}")


Converged after 10 iterations.
Cost Grid (each cell's movement cost):
[[6 1 4 4 8]
 [4 6 3 5 8]
 [7 9 9 2 7]
 [8 8 9 2 6]
 [9 5 4 1 4]]

Shortest Distance to Goal (Parallel Cellular Computation):
[[ 0.  1.  5.  9. 17.]
 [ 4.  7.  8. 13. 21.]
 [11. 16. 17. 15. 22.]
 [19. 24. 26. 17. 23.]
 [28. 27. 22. 18. 22.]]

Estimated shortest distance from start to goal: 22.00
